language: python

#Django version     Python versions
#1.11               2.7, 3.4, 3.5, 3.6
#2.0                3.4, 3.5, 3.6, 3.7
#2.1, 2.2           3.5, 3.6, 3.7

matrix:

  include:
    - python: 2.7
      env: DJANGO_VERSION="Django>=1.11,<1.12"

    - python: 3.4
      env: DJANGO_VERSION="Django>=2.0,<2.1"
    - python: 3.5
      env: DJANGO_VERSION="Django>=2.0,<2.1"
    - python: 3.6
      env: DJANGO_VERSION="Django>=2.0,<2.1"
    - python: 3.7
      env: DJANGO_VERSION="Django>=2.0,<2.1"
      dist: xenial
      sudo: true

    - python: 3.5
      env: DJANGO_VERSION="Django>=2.1,<2.2"
    - python: 3.6
      env: DJANGO_VERSION="Django>=2.1,<2.2"
    - python: 3.7
      env: DJANGO_VERSION="Django>=2.1,<2.2"
      dist: xenial
      sudo: true

before_install:
  - export DJANGO_SETTINGS_MODULE=sites.test.settings

install:
  - pip install "$DJANGO_VERSION"
  - pip install -r requirements.test.txt
  - pip install codecov

script: coverage run manage.py test tests

notifications:
  email: false

after_success:
  - codecov

