language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

env:
  - DJANGO_VERSION=1.8.13
  - DJANGO_VERSION=1.9.6
before_install:
  - export DJANGO_SETTINGS_MODULE=sites.test.settings

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

script: python manage.py test tests

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)