language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO_VERSION=1.8.13
  - DJANGO_VERSION=1.9.6
  - DJANGO_VERSION=1.10.1
before_install:
  - export DJANGO_SETTINGS_MODULE=sites.test.settings

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install codecov

script: coverage run manage.py test tests

notifications:
  email: false

after_success:
  - codecov